import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { PlaywrightAdapter, type BrowserClock, type UiPage } from "../src/browser.js";
import { parseAgentObservation } from "../src/browser-runtime.js";
import { parseHandlerCatalog } from "../src/handlers.js";
import { OBSERVATION_VERSION, type ObservationV1 } from "../src/types.js";

function observation(mode: ObservationV1["mode"] = "idle", markers = ["zpg-arena"]): ObservationV1 { return { version: OBSERVATION_VERSION, observedAt: "2026-09-20T10:00:00.000Z", sourceVersion: "fixture", freshness: "fresh", mode, capabilities: [], progressionKnown: true, health: "known_safe", cooldowns: { "zpg-arena": "2026-09-20T09:00:00.000Z" }, rawShape: markers }; }
const handler = parseHandlerCatalog({ schemaVersion: "handler-catalog/v1", enabled: true, handlers: [{ schemaVersion: "handler/v1", handler: "arena.zpg.start", version: 1, priority: 1, enabled: true, reviewedSourceURL: "https://wiki.godville.net/%D0%90%D1%80%D0%B5%D0%BD%D0%B0", verifiedAt: "2026-09-20T00:00:00.000Z", match: { role: "button", text: "Start ZPG" }, scope: { modes: ["idle"], requiredMarkers: ["zpg-arena"], deadline: { endSecond: 179, safetyMarginMs: 9000 } }, precondition: { kind: "all", conditions: [{ kind: "equals", field: "mode", value: "idle" }, { kind: "contains", field: "rawShape", value: "zpg-arena" }] }, cost: { maxPrana: 0, maxCharges: 0 }, action: { reactionDelayMs: [10, 10], clickOffsetPx: 2, clickJigglePx: 1 }, postcondition: { condition: { kind: "equals", field: "mode", value: "arena" }, timeoutMs: 100, pollIntervalMs: 25 } }] }).handlers[0]!;
function page(click: () => void, count = 1, onMove?: () => void): UiPage { return { getByRole: (_role, options) => ({ count: async () => count, nth: () => ({ isVisible: async () => options.name === "Start ZPG", isEnabled: async () => true, boundingBox: async () => ({ x: 10, y: 20, width: 100, height: 30 }), click: async ({ position }) => { assert.ok(position.x >= 3 && position.x <= 97); assert.ok(position.y >= 3 && position.y <= 27); click(); } }) }), mouse: { move: async () => { onMove?.(); } } }; }
function clock(second = 60): BrowserClock { let milliseconds = Date.UTC(2026, 8, 20, 10, 0, second); return { random: () => 0.5, now: () => new Date(milliseconds), wait: async (delay) => { milliseconds += delay; } }; }
test("clicks once after fresh recheck and confirms postcondition", async () => { let state = "idle" as ObservationV1["mode"], clicks = 0, journals = 0; const adapter = new PlaywrightAdapter(page(() => { clicks++; state = "arena"; }), async () => observation(state), clock(), undefined, "fixture"); const result = await adapter.execute(handler, { beforeClick: async () => { journals++; return true; } }); assert.equal(result.state, "CONFIRMED"); assert.equal(clicks, 1); assert.equal(journals, 1); });
test("skips at HH:02:59 due to safety margin", async () => { let clicks = 0; const adapter = new PlaywrightAdapter(page(() => { clicks++; }), async () => observation(), clock(179), undefined, "fixture"); const result = await adapter.execute(handler, { beforeClick: async () => true }); assert.equal(result.state, "SKIPPED"); assert.match(result.reason, /deadline/); assert.equal(clicks, 0); });
test("requires fresh ZPG marker and journal gate", async () => { let clicks = 0; const noMarker = new PlaywrightAdapter(page(() => { clicks++; }), async () => observation("idle", []), clock(), undefined, "fixture"); assert.equal((await noMarker.execute(handler, { beforeClick: async () => true })).state, "SKIPPED"); const noJournal = new PlaywrightAdapter(page(() => { clicks++; }), async () => observation(), clock(), undefined, "fixture"); assert.equal((await noJournal.execute(handler, {})).state, "SKIPPED"); assert.equal(clicks, 0); });
test("cancellation before the journal skips, while cancellation after its gate is ambiguous", async () => { const beforeGate = new AbortController(); let journals = 0, clicks = 0; const pre = new PlaywrightAdapter(page(() => { clicks++; }), async () => observation(), clock(), undefined, "fixture"); const skipped = await pre.execute(handler, { signal: beforeGate.signal, beforeClick: async () => { journals++; return true; }, onObservation: async (_observation, phase) => { if (phase === "recheck") beforeGate.abort(); } }); assert.equal(skipped.state, "SKIPPED"); assert.equal(journals, 0); const afterGate = new AbortController(); const post = new PlaywrightAdapter(page(() => { clicks++; }, 1, () => afterGate.abort()), async () => observation(), clock(), undefined, "fixture"); const ambiguous = await post.execute(handler, { signal: afterGate.signal, beforeClick: async () => { journals++; return true; } }); assert.equal(ambiguous.state, "AMBIGUOUS"); assert.equal(clicks, 0); assert.equal(journals, 1); });
test("rejects link roles and unsafe ZPG manifests", () => { assert.throws(() => parseHandlerCatalog({ schemaVersion: "handler-catalog/v1", enabled: true, handlers: [{ ...handler, match: { role: "link", text: "Start ZPG" } }] })); assert.throws(() => parseHandlerCatalog({ schemaVersion: "handler-catalog/v1", enabled: true, handlers: [{ ...handler, scope: { modes: ["idle"], requiredMarkers: ["ordinary-arena"] } }] })); });
test("DOM observer accepts only an explicit JSON observation contract", () => { assert.equal(parseAgentObservation(JSON.stringify(observation())).mode, "idle"); assert.throws(() => parseAgentObservation("<script>alert(1)</script>")); });
test("example catalog is valid and disabled until a reviewed DOM contract exists", () => { const catalog = parseHandlerCatalog(JSON.parse(readFileSync("config/handlers.example.json", "utf8"))); assert.equal(catalog.enabled, false); assert.equal(catalog.handlers[0]!.enabled, false); });
